# Generated by Django 5.0.2 on 2024-04-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobileno', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelname', models.CharField(max_length=20)),
                ('channellang', models.CharField(max_length=20)),
                ('channeldes', models.CharField(max_length=20)),
                ('channelamount', models.IntegerField()),
                ('channeltype', models.CharField(max_length=20)),
                ('packname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddh.pack')),
            ],
        ),
        migrations.CreateModel(
            name='User_pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pack_status', models.CharField(max_length=50)),
                ('datef', models.DateField()),
                ('enddat', models.DateField()),
                ('packname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddh.pack')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddh.userdata')),
            ],
        ),
    ]
