# Generated by Django 5.0.2 on 2024-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_pack',
            name='days_remaining',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
